
### 1. Listar todos os alunos
GET http://localhost:3000/alunos

### 2. Criar um novo aluno
POST http://localhost:3000/aluno/create
Content-Type: application/json

{
  "nome": "João Silva",
  "genero": "Masculino",
  "dataNascimento": "2010-05-12T00:00:00.000Z",
  "telefone": "99999-9999",
  "anoEscolar": "5º Ano",
  "alfabetizado": true,
  "turno": "Manhã",
  "turmaId":"06652edb-2dfa-4ff9-b4f4-4e44179a4bd6"
}

### 3. Atualizar um aluno
PUT http://localhost:3000/aluno/93afca09-e0a6-4640-ac45-35763f2c02c6
Content-Type: application/json

{
  "nome": "João Silva Atualizado",
  "genero": "Masculino",
  "dataNascimento": "2010-05-12T00:00:00.000Z",
  "telefone": "88888-8888",
  "anoEscolar": "7º Ano",
  "alfabetizado": true,
  "turno": "Tarde"
}

### 4. Deletar um aluno
DELETE http://localhost:3000/aluno/ebcbc158-6416-4cce-b57a-8985b574496b
