
### 1. Lista todos os dados adicionais
GET http://localhost:3000/dadosAdicionais

### 2. Faz um post de dados adicionai
POST http://localhost:3000/dadosAdicionais/create
Content-Type: application/json

{
  "cpf_nota_fiscal": true,
  "tipo_residencia": "Apartamento",
  "numero_comodos": 2,
  "possui_banheiro": true,
  "possui_agua": true,
  "possui_luz": true,
  "alunoId": "93afca09-e0a6-4640-ac45-35763f2c02c6"
}

### 3. atualiza dados adicionais
PUT http://localhost:3000/dadosAdicionais/9a5cf79f-de3a-4f65-bc7e-b96789bc552c
Content-Type: application/json

{
  "cpf_nota_fiscal": true,
  "tipo_residencia": "Casa",
  "numero_comodos": 2,
  "possui_banheiro": true,
  "possui_agua": true,
  "possui_luz": true,
  "alunoId": "93afca09-e0a6-4640-ac45-35763f2c02c6"
}

### 4. Deleta um dado adicional
DELETE http://localhost:3000/dadosAdicionais/1aac7f3f-3407-4a54-a55d-cbbc9f1b25b4
